schema = 1

[project]
layout_cap = 32
id = "0f342a96-54f7-425f-b9b3-052d53c072b1"
state = "ready"
name = "BattleTanx"
title = "BATTLETANX"
names_from = "us"
versions = [ "us",]
default_compiler = "gcc-2.7.2-kmc"

[workspace]
id = "eba651b1-2b5f-44d1-a224-dd5a58dd8e5d"

[paths]
declaration_evidence = []
roms = "roms"
build = "build"
work = "build/work"
drafts = "build/drafts"
src = "src"
include = [ "include",]
asm = "asm"
tools = "tools"

[build]
ld = "policy:mips_ld"
objcopy = "policy:mips_objcopy"
splat = "policy:splat"
as = "policy:mips_as"
cpp = "policy:cpp"
asflags = [ "-march=vr4300", "-mabi=32", "-EB", "--no-pad-sections",]
cppflags = [ "-P", "-undef", "-nostdinc", "-D_LANGUAGE_C", "-DF3DEX_GBI_2", "-D__GNUC__=2",]
sn64_asflags = [ "-mips3",]

[units]
func_80119568_us = "ido-7.1"
func_8007967C = "ido-7.1"
func_80079684 = "ido-7.1"
func_8007C298 = "ido-7.1"
func_8007C33C = "ido-7.1"
func_800805D0 = "ido-7.1"
func_80085460 = "ido-7.1"
func_80085468 = "ido-7.1"
func_800917C4 = "ido-7.1"
func_80093F34 = "ido-7.1"
func_800949B8 = "ido-7.1"
func_80096784 = "gcc-2.8.1-sn64"
func_80097C24 = "ido-7.1"
func_8009E39C = "ido-7.1"
func_800A424C = "ido-7.1"
func_800A42BC = "ido-7.1"
func_800A4D1C = "ido-7.1"
func_800A66C0 = "ido-7.1"
func_800A7548 = "ido-7.1"
func_800A76A0 = "ido-7.1"
func_800AB200 = "ido-7.1"
func_800ABFA0 = "ido-7.1"
func_800E3460 = "ido-7.1"
func_800E3470 = "ido-7.1"
func_800E3480 = "ido-7.1"
func_800E349C = "ido-7.1"
func_800E3C18 = "ido-7.1"
func_800E480C = "ido-7.1"
func_800E4814_us = "ido-7.1"
func_800E5198 = "ido-7.1"
func_800E566C = "ido-7.1"
func_800E99D4 = "ido-7.1"
func_800EA1B0 = "ido-7.1"
func_800EBBB4_us = "ido-7.1"
func_80106D00 = "ido-7.1"
func_80106D08_us = "ido-7.1"
func_80107168_us = "ido-7.1"
func_80107704_us = "ido-7.1"
func_80109354 = "ido-7.1"
func_8010BC08 = "ido-7.1"
func_801109B8_us = "ido-7.1"
func_80110AAC_us = "ido-7.1"
func_80110CA0 = "ido-7.1"
func_801145D0 = "ido-7.1"
func_801147A0 = "ido-7.1"
func_80114828 = "ido-7.1"
func_80115474 = "ido-7.1"
func_8011588C = "ido-7.1"
func_80115C80 = "ido-7.1"
func_8011954C = "ido-7.1"
func_80119570_us = "ido-7.1"
func_80119B60 = "ido-7.1"
func_80119BB4 = "ido-7.1"
func_80119C34 = "ido-7.1"
func_80119CE8_us = "ido-7.1"
func_80119F70 = "ido-7.1"
func_8011A134 = "ido-7.1"
func_8011AB74_us = "ido-7.1"
func_8011B1A0 = "ido-7.1"
func_8011B2A4 = "ido-7.1"
func_8011B7BC = "ido-7.1"
func_8011B8F0 = "ido-7.1"
func_8011B9E0 = "ido-7.1"
func_8011BDE4 = "ido-7.1"
func_8011C150 = "ido-7.1"
func_8011C180 = "ido-7.1"
func_8011C300 = "ido-7.1"
func_8011C39C_us = "ido-7.1"
func_8011C3A4_us = "ido-7.1"
func_8011D0E0 = "ido-7.1"
func_8011D100 = "ido-7.1"
func_8011D3DC = "ido-7.1"
func_8011D6D0 = "ido-7.1"
func_8011DC00_us = "ido-7.1"
func_8011DC60 = "ido-7.1"
func_8011DC98 = "ido-7.1"
func_8011DD40_us = "ido-7.1"
func_8011E3F0 = "ido-7.1"
func_8011E434 = "ido-7.1"
func_8011E488 = "ido-7.1"
func_8011E564 = "ido-7.1"
func_8011E6B0_us = "ido-5.3"
func_8011ECA4 = "ido-7.1"
func_8011F7F0 = "ido-7.1"
func_80121F10 = "ido-7.1"

[build.resident_mappings]
[[build.resident_mappings.us]]
address = 2147946496
end = 24576
start = 4096
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2147971224
end = 28944
start = 28824
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2147973896
end = 31504
start = 31496
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2147980712
end = 38320
start = 38312
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2147996716
end = 54320
start = 54316
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148000056
end = 57664
start = 57656
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148033340
end = 91000
start = 90940
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148052236
end = 109840
start = 109836
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148077272
end = 134880
start = 134872
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148079468
end = 137156
start = 137068
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148089132
end = 146736
start = 146732
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148089948
end = 147552
start = 147548
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148101748
end = 159360
start = 159348
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148140024
end = 197632
start = 197624
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148142292
end = 201072
start = 199892
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148151112
end = 209008
start = 208712
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148163556
end = 221168
start = 221156
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148169288
end = 226896
start = 226888
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148178964
end = 236576
start = 236564
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148340740
end = 398652
start = 398340
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148390808
end = 448880
start = 448408
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148407828
end = 465440
start = 465428
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148422300
end = 479904
start = 479900
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148453380
end = 511004
start = 510980
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148559700
end = 617312
start = 617300
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148587588
end = 645200
start = 645188
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148589912
end = 656512
start = 647512
table_entry_bias = 2147483648

[[build.resident_mappings.us]]
address = 2148682044
end = 739648
start = 739644
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148683448
end = 741056
start = 741048
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148684868
end = 742480
start = 742468
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148684956
end = 742560
start = 742556
table_entry_bias = 0

[[build.resident_mappings.us]]
address = 2148685136
end = 880704
start = 742736
table_entry_bias = 0

[build.unit_cflags]
func_801145D0 = [ "-O1",]
func_80115474 = [ "-O1",]
func_8011588C = [ "-O1",]
func_80115C80 = [ "-O1",]
func_8011D100 = [ "-O1",]
func_80121F10 = [ "-O1",]

[version.us]
baserom = "roms/baserom.us.z64"
baserom_sha1 = "535860d941738ac1210c20a9b80114fea0e0ff17"
split = "versions/us/BattleTanx.yaml"
symbols = "versions/us/symbol_addrs.txt"
macros = [ "VERSION_US",]
cartridge_id = "NUS-NBXE-0"
region = "North America"
description = "NTSC release."

[compilers."gcc-2.7.2-kmc"]
cflags = [ "-G0", "-mips3", "-mgp32", "-mfp32", "-O2",]

[compilers."gcc-2.8.1-sn64"]
cflags = [ "-G0", "-mips3", "-O2", "-mgas", "-meb", "-mcpu=VR4300", "-mhard-float", "-mgp32", "-mfp64", "-mno-fix4300",]

[compilers."ido-5.3"]
cflags = [ "-c", "-G0", "-non_shared", "-mips2", "-O2",]

[compilers."ido-7.1"]
cflags = [ "-c", "-G0", "-non_shared", "-mips2", "-O2",]
