# Generated by unbake. Do not edit; unbake regenerates it from config.toml and versions/.
us.BASEROM := roms/baserom.us.z64
us.DEFINES := -DVERSION_US
us.MAP := 0x0:0x0:0x1000 0x80071000:0x1000:0xD6040 0xD7040:0xD7040:0x728FC0 0x80071000:0x1000:0x5000 0x80077098:0x7098:0x78 0x80077B08:0x7B08:0x8 0x800795A8:0x95A8:0x8 0x8007D42C:0xD42C:0x4 0x8007E138:0xE138:0x8 0x8008633C:0x1633C:0x3C 0x8008AD0C:0x1AD0C:0x4 0x80090ED8:0x20ED8:0x8 0x8009176C:0x2176C:0x58 0x80093D2C:0x23D2C:0x4 0x8009405C:0x2405C:0x4 0x80096E74:0x26E74:0xC 0x800A03F8:0x303F8:0x8 0x800A0CD4:0x30CD4:0x49C 0x800A2F48:0x32F48:0x128 0x800A5FE4:0x35FE4:0xC 0x800A7648:0x37648:0x8 0x800A9C14:0x39C14:0xC 0x800D1404:0x61404:0x138 0x800DD798:0x6D798:0x1D8 0x800E1A14:0x71A14:0xC 0x800E529C:0x7529C:0x4 0x800ECC04:0x7CC04:0x18 0x80106B54:0x96B54:0xC 0x8010D844:0x9D844:0xC 0x8010E158:0x9E158:0x2328 0x8012493C:0xB493C:0x4 0x80124EB8:0xB4EB8:0x8 0x80125444:0xB5444:0xC 0x8012549C:0xB549C:0x4 0x80125550:0xB5550:0x21AF0
us.S.00000000 := 0 24632
us.U.func_80076038 := 0x80076038:0x6038:0x30
us.S.00006068 := 24680 532
us.U.func_8007627C := 0x8007627C:0x627C:0x114
us.S.00006390 := 25488 5536
us.U.func_80077930 := 0x80077930:0x7930:0x9C
us.S.000079CC := 31180 108
us.U.func_80077A38 := 0x80077A38:0x7A38:0x98
us.S.00007AD0 := 31440 4800
us.U.func_80078D90 := 0x80078D90:0x8D90:0x9C
us.S.00008E2C := 36396 308
us.U.func_80078F60_us := 0x80078F60:0x8F60:0x10
us.S.00008F70 := 36720 1120
us.U.func_800793D0 := 0x800793D0:0x93D0:0xA4
us.S.00009474 := 38004 520
us.U.func_8007967C := 0x8007967C:0x967C:0x8
us.U.func_80079684 := 0x80079684:0x9684:0x8
us.S.0000968C := 38540 820
us.U.func_800799C0_us := 0x800799C0:0x99C0:0x10
us.S.000099D0 := 39376 140
us.U.func_80079A5C := 0x80079A5C:0x9A5C:0x58
us.S.00009AB4 := 39604 1096
us.U.func_80079EFC := 0x80079EFC:0x9EFC:0xA8
us.S.00009FA4 := 40868 712
us.U.func_8007A26C_us := 0x8007A26C:0xA26C:0x100
us.S.0000A36C := 41836 1844
us.U.func_8007AAA0 := 0x8007AAA0:0xAAA0:0x10
us.U.func_8007AAB0 := 0x8007AAB0:0xAAB0:0x10
us.U.func_8007AAC0 := 0x8007AAC0:0xAAC0:0x24
us.U.func_8007AAE4_us := 0x8007AAE4:0xAAE4:0x10
us.U.func_8007AAF4_us := 0x8007AAF4:0xAAF4:0x10
us.S.0000AB04 := 43780 1752
us.U.func_8007B1DC_us := 0x8007B1DC:0xB1DC:0x10
us.S.0000B1EC := 45548 4268
us.U.func_8007C298 := 0x8007C298:0xC298:0x8
us.S.0000C2A0 := 49824 156
us.U.func_8007C33C := 0x8007C33C:0xC33C:0x8
us.S.0000C344 := 49988 916
us.U.func_8007C6D8 := 0x8007C6D8:0xC6D8:0x28
us.S.0000C700 := 50944 2808
us.U.func_8007D1F8 := 0x8007D1F8:0xD1F8:0xA8
us.S.0000D2A0 := 53920 228
us.U.func_8007D384 := 0x8007D384:0xD384:0xA8
us.S.0000D42C := 54316 3348
us.U.func_8007E140_us := 0x8007E140:0xE140:0x10
us.S.0000E150 := 57680 2792
us.U.func_8007EC38 := 0x8007EC38:0xEC38:0xB0
us.U.func_8007ECE8 := 0x8007ECE8:0xECE8:0xB0
us.U.func_8007ED98 := 0x8007ED98:0xED98:0xB0
us.U.func_8007EE48 := 0x8007EE48:0xEE48:0xB0
us.S.0000EEF8 := 61176 312
us.U.func_8007F030_us := 0x8007F030:0xF030:0x10
us.S.0000F040 := 61504 32
us.U.func_8007F060 := 0x8007F060:0xF060:0x10
us.S.0000F070 := 61552 3832
us.U.func_8007FF68 := 0x8007FF68:0xFF68:0xB4
us.U.func_8008001C_us := 0x8008001C:0x1001C:0x100
us.S.0001011C := 65820 1188
us.U.func_800805C0_us := 0x800805C0:0x105C0:0x10
us.U.func_800805D0 := 0x800805D0:0x105D0:0xC
us.U.func_800805DC := 0x800805DC:0x105DC:0xA0
us.S.0001067C := 67196 5044
us.U.func_80081A30 := 0x80081A30:0x11A30:0x10
us.U.func_80081A40_us := 0x80081A40:0x11A40:0x10
us.S.00011A50 := 72272 112
us.U.func_80081AC0_us := 0x80081AC0:0x11AC0:0x10
us.S.00011AD0 := 72400 1776
us.U.func_800821C0 := 0x800821C0:0x121C0:0x10
us.S.000121D0 := 74192 12640
us.U.func_80085330 := 0x80085330:0x15330:0x98
us.S.000153C8 := 86984 152
us.U.func_80085460 := 0x80085460:0x15460:0x8
us.U.func_80085468 := 0x80085468:0x15468:0x8
us.S.00015470 := 87152 28268
us.U.func_8008C2DC_us := 0x8008C2DC:0x1C2DC:0x10
us.S.0001C2EC := 115436 17632
us.U.func_800907CC_us := 0x800907CC:0x207CC:0x100
us.S.000208CC := 133324 1604
us.U.func_80090F10 := 0x80090F10:0x20F10:0x84
us.S.00020F94 := 135060 1652
us.U.func_80091608 := 0x80091608:0x21608:0xB0
us.U.func_800916B8 := 0x800916B8:0x216B8:0xB4
us.S.0002176C := 137068 88
us.U.func_800917C4 := 0x800917C4:0x217C4:0x14
us.U.func_800917D8 := 0x800917D8:0x217D8:0x3C
us.S.00021814 := 137236 1264
us.U.func_80091D04 := 0x80091D04:0x21D04:0xC
us.S.00021D10 := 138512 2084
us.U.func_80092534_us := 0x80092534:0x22534:0x200
us.S.00022734 := 141108 6144
us.U.func_80093F34 := 0x80093F34:0x23F34:0x8
us.S.00023F3C := 147260 2684
us.U.func_800949B8 := 0x800949B8:0x249B8:0x20
us.S.000249D8 := 149976 7560
us.U.func_80096760 := 0x80096760:0x26760:0x8
us.S.00026768 := 157544 28
us.U.func_80096784 := 0x80096784:0x26784:0xB0
us.S.00026834 := 157748 200
us.U.func_800968FC := 0x800968FC:0x268FC:0x24
us.S.00026920 := 157984 4700
us.U.func_80097B7C := 0x80097B7C:0x27B7C:0xA8
us.U.func_80097C24 := 0x80097C24:0x27C24:0x40
us.S.00027C64 := 162916 8308
us.U.func_80099CD8 := 0x80099CD8:0x29CD8:0xB8
us.S.00029D90 := 171408 17932
us.U.func_8009E39C := 0x8009E39C:0x2E39C:0x8
us.S.0002E3A4 := 189348 19200
us.U.func_800A2EA4 := 0x800A2EA4:0x32EA4:0xA4
us.S.00032F48 := 208712 3560
us.U.func_800A3D30 := 0x800A3D30:0x33D30:0xB0
us.S.00033DE0 := 212448 1132
us.U.func_800A424C := 0x800A424C:0x3424C:0x8
us.U.func_800A4254 := 0x800A4254:0x34254:0x50
us.U.func_800A42A4 := 0x800A42A4:0x342A4:0xC
us.U.func_800A42B0 := 0x800A42B0:0x342B0:0xC
us.U.func_800A42BC := 0x800A42BC:0x342BC:0x8
us.U.func_800A42C4_us := 0x800A42C4:0x342C4:0xC
us.S.000342D0 := 213712 152
us.U.func_800A4368_us := 0x800A4368:0x34368:0xC
us.S.00034374 := 213876 1776
us.U.func_800A4A64 := 0x800A4A64:0x34A64:0xC8
us.S.00034B2C := 215852 484
us.U.func_800A4D10_us := 0x800A4D10:0x34D10:0xC
us.U.func_800A4D1C := 0x800A4D1C:0x34D1C:0x18
us.S.00034D34 := 216372 1204
us.U.func_800A51E8 := 0x800A51E8:0x351E8:0xC4
us.U.func_800A52AC := 0x800A52AC:0x352AC:0x9C
us.S.00035348 := 217928 1696
us.U.func_800A59E8 := 0x800A59E8:0x359E8:0xBC
us.S.00035AA4 := 219812 3084
us.U.func_800A66B0_us := 0x800A66B0:0x366B0:0x10
us.U.func_800A66C0 := 0x800A66C0:0x366C0:0x8
us.S.000366C8 := 222920 536
us.U.func_800A68E0_us := 0x800A68E0:0x368E0:0x10
us.U.func_800A68F0_us := 0x800A68F0:0x368F0:0x10
us.S.00036900 := 223488 1296
us.U.func_800A6E10 := 0x800A6E10:0x36E10:0x20
us.S.00036E30 := 224816 1176
us.U.func_800A72C8 := 0x800A72C8:0x372C8:0x60
us.S.00037328 := 226088 388
us.U.func_800A74AC := 0x800A74AC:0x374AC:0x9C
us.U.func_800A7548 := 0x800A7548:0x37548:0x8
us.U.func_800A7550 := 0x800A7550:0x37550:0x9C
us.S.000375EC := 226796 180
us.U.func_800A76A0 := 0x800A76A0:0x376A0:0x1C
us.S.000376BC := 227004 1620
us.U.func_800A7D10 := 0x800A7D10:0x37D10:0xAC
us.S.00037DBC := 228796 1076
us.U.func_800A81F0 := 0x800A81F0:0x381F0:0x4C
us.S.0003823C := 229948 5472
us.U.func_800A979C := 0x800A979C:0x3979C:0xB4
us.S.00039850 := 235600 756
us.U.func_800A9B44 := 0x800A9B44:0x39B44:0x2C
us.U.func_800A9B70 := 0x800A9B70:0x39B70:0xA4
us.S.00039C14 := 236564 1644
us.U.func_800AA280 := 0x800AA280:0x3A280:0xA8
us.U.func_800AA328 := 0x800AA328:0x3A328:0xA8
us.S.0003A3D0 := 238544 3632
us.U.func_800AB200 := 0x800AB200:0x3B200:0x8
us.S.0003B208 := 242184 1036
us.U.func_800AB614 := 0x800AB614:0x3B614:0x8
us.S.0003B61C := 243228 832
us.U.func_800AB95C := 0x800AB95C:0x3B95C:0xA0
us.S.0003B9FC := 244220 1444
us.U.func_800ABFA0 := 0x800ABFA0:0x3BFA0:0x8
us.S.0003BFA8 := 245672 40
us.U.func_800ABFD0 := 0x800ABFD0:0x3BFD0:0xA0
us.S.0003C070 := 245872 608
us.U.func_800AC2D0_us := 0x800AC2D0:0x3C2D0:0x10
us.S.0003C2E0 := 246496 50288
us.U.func_800B8750 := 0x800B8750:0x48750:0xA4
us.U.func_800B87F4_us := 0x800B87F4:0x487F4:0x10
us.S.00048804 := 296964 89260
us.U.func_800CE4B0 := 0x800CE4B0:0x5E4B0:0xA4
us.S.0005E554 := 386388 62612
us.U.func_800DD9E8_us := 0x800DD9E8:0x6D9E8:0x18
us.U.func_800DDA00_us := 0x800DDA00:0x6DA00:0x8
us.S.0006DA08 := 449032 668
us.U.func_800DDCA4 := 0x800DDCA4:0x6DCA4:0x28
us.S.0006DCCC := 449740 11828
us.U.func_800E0B00 := 0x800E0B00:0x70B00:0xC4
us.S.00070BC4 := 461764 3652
us.U.func_800E1A08_us := 0x800E1A08:0x71A08:0xC
us.S.00071A14 := 465428 3072
us.U.func_800E2614_us := 0x800E2614:0x72614:0xC
us.U.func_800E2620_us := 0x800E2620:0x72620:0xC
us.S.0007262C := 468524 3636
us.U.func_800E3460 := 0x800E3460:0x73460:0x10
us.U.func_800E3470 := 0x800E3470:0x73470:0x10
us.U.func_800E3480 := 0x800E3480:0x73480:0x1C
us.U.func_800E349C := 0x800E349C:0x7349C:0x18
us.U.func_800E34B4 := 0x800E34B4:0x734B4:0xA0
us.S.00073554 := 472404 1732
us.U.func_800E3C18 := 0x800E3C18:0x73C18:0x1C
us.S.00073C34 := 474164 3032
us.U.func_800E480C := 0x800E480C:0x7480C:0x8
us.U.func_800E4814_us := 0x800E4814:0x74814:0x8
us.S.0007481C := 477212 1320
us.U.func_800E4D44 := 0x800E4D44:0x74D44:0xB4
us.S.00074DF8 := 478712 928
us.U.func_800E5198 := 0x800E5198:0x75198:0x8
us.S.000751A0 := 479648 24
us.U.func_800E51B8_us := 0x800E51B8:0x751B8:0x8
us.S.000751C0 := 479680 1196
us.U.func_800E566C := 0x800E566C:0x7566C:0x1C
us.S.00075688 := 480904 5096
us.U.func_800E6A70_us := 0x800E6A70:0x76A70:0x8
us.S.00076A78 := 486008 412
us.U.func_800E6C14 := 0x800E6C14:0x76C14:0x48
us.S.00076C5C := 486492 72
us.U.func_800E6CA4 := 0x800E6CA4:0x76CA4:0xB4
us.S.00076D58 := 486744 584
us.U.func_800E6FA0_us := 0x800E6FA0:0x76FA0:0x8
us.U.func_800E6FA8_us := 0x800E6FA8:0x76FA8:0x8
us.S.00076FB0 := 487344 1896
us.U.func_800E7718_us := 0x800E7718:0x77718:0xC
us.S.00077724 := 489252 408
us.U.func_800E78BC_us := 0x800E78BC:0x778BC:0xC
us.U.func_800E78C8_us := 0x800E78C8:0x778C8:0xC
us.U.func_800E78D4_us := 0x800E78D4:0x778D4:0xC
us.U.func_800E78E0_us := 0x800E78E0:0x778E0:0xC
us.U.func_800E78EC_us := 0x800E78EC:0x778EC:0xC
us.U.func_800E78F8_us := 0x800E78F8:0x778F8:0xC
us.U.func_800E7904_us := 0x800E7904:0x77904:0xC
us.U.func_800E7910_us := 0x800E7910:0x77910:0xC
us.U.func_800E791C_us := 0x800E791C:0x7791C:0xC
us.U.func_800E7928_us := 0x800E7928:0x77928:0xC
us.S.00077934 := 489780 8032
us.U.func_800E9894 := 0x800E9894:0x79894:0xAC
us.S.00079940 := 497984 148
us.U.func_800E99D4 := 0x800E99D4:0x799D4:0xC
us.S.000799E0 := 498144 64
us.U.func_800E9A20_us := 0x800E9A20:0x79A20:0x8
us.U.func_800E9A28_us := 0x800E9A28:0x79A28:0x8
us.S.00079A30 := 498224 884
us.U.func_800E9DA4 := 0x800E9DA4:0x79DA4:0xB8
us.S.00079E5C := 499292 852
us.U.func_800EA1B0 := 0x800EA1B0:0x7A1B0:0x8
us.S.0007A1B8 := 500152 68
us.U.func_800EA1FC := 0x800EA1FC:0x7A1FC:0xA8
us.S.0007A2A4 := 500388 2632
us.U.func_800EACEC_us := 0x800EACEC:0x7ACEC:0x40
us.S.0007AD2C := 503084 848
us.U.func_800EB07C_us := 0x800EB07C:0x7B07C:0x6C
us.S.0007B0E8 := 504040 256
us.U.func_800EB1E8_us := 0x800EB1E8:0x7B1E8:0x40
us.S.0007B228 := 504360 536
us.U.func_800EB440_us := 0x800EB440:0x7B440:0x3C
us.S.0007B47C := 504956 40
us.U.func_800EB4A4_us := 0x800EB4A4:0x7B4A4:0x40
us.S.0007B4E4 := 505060 496
us.U.func_800EB6D4_us := 0x800EB6D4:0x7B6D4:0x48
us.U.func_800EB71C_us := 0x800EB71C:0x7B71C:0x48
us.U.func_800EB764_us := 0x800EB764:0x7B764:0x48
us.U.func_800EB7AC_us := 0x800EB7AC:0x7B7AC:0x6C
us.S.0007B818 := 505880 924
us.U.func_800EBBB4_us := 0x800EBBB4:0x7BBB4:0x8
us.U.func_800EBBBC_us := 0x800EBBBC:0x7BBBC:0x40
us.S.0007BBFC := 506876 376
us.U.func_800EBD74_us := 0x800EBD74:0x7BD74:0x40
us.S.0007BDB4 := 507316 184
us.U.func_800EBE6C_us := 0x800EBE6C:0x7BE6C:0x40
us.S.0007BEAC := 507564 6500
us.U.func_800ED810 := 0x800ED810:0x7D810:0xAC
us.S.0007D8BC := 514236 4912
us.U.func_800EEBEC := 0x800EEBEC:0x7EBEC:0xB4
us.U.func_800EECA0 := 0x800EECA0:0x7ECA0:0xBC
us.S.0007ED5C := 519516 13252
us.U.func_800F2120_us := 0x800F2120:0x82120:0x8
us.S.00082128 := 532776 3820
us.U.func_800F3014 := 0x800F3014:0x83014:0xB4
us.S.000830C8 := 536776 8288
us.U.func_800F5128 := 0x800F5128:0x85128:0x50
us.U.func_800F5178 := 0x800F5178:0x85178:0xEC
us.S.00085264 := 545380 72348
us.U.func_80106D00 := 0x80106D00:0x96D00:0x8
us.U.func_80106D08_us := 0x80106D08:0x96D08:0x8
us.U.func_80106D10_us := 0x80106D10:0x96D10:0x8
us.S.00096D18 := 617752 1104
us.U.func_80107168_us := 0x80107168:0x97168:0x8
us.S.00097170 := 618864 1428
us.U.func_80107704_us := 0x80107704:0x97704:0x8
us.S.0009770C := 620300 7240
us.U.func_80109354 := 0x80109354:0x99354:0x10
us.S.00099364 := 627556 10404
us.U.func_8010BC08 := 0x8010BC08:0x9BC08:0x8
us.S.0009BC10 := 637968 8384
us.U.func_8010DCD0 := 0x8010DCD0:0x9DCD0:0xA8
us.S.0009DD78 := 646520 11328
us.U.func_801109B8_us := 0x801109B8:0xA09B8:0x8
us.S.000A09C0 := 657856 236
us.U.func_80110AAC_us := 0x80110AAC:0xA0AAC:0x8
us.S.000A0AB4 := 658100 492
us.U.func_80110CA0 := 0x80110CA0:0xA0CA0:0x84
us.S.000A0D24 := 658724 14508
us.U.func_801145D0 := 0x801145D0:0xA45D0:0xD0
us.S.000A46A0 := 673440 256
us.U.func_801147A0 := 0x801147A0:0xA47A0:0x88
us.U.func_80114828 := 0x80114828:0xA4828:0x30
us.S.000A4858 := 673880 3100
us.U.func_80115474 := 0x80115474:0xA5474:0x418
us.U.func_8011588C := 0x8011588C:0xA588C:0x198
us.S.000A5A24 := 678436 604
us.U.func_80115C80 := 0x80115C80:0xA5C80:0xFC
us.S.000A5D7C := 679292 14288
us.U.func_8011954C := 0x8011954C:0xA954C:0x1C
us.U.func_80119568_us := 0x80119568:0xA9568:0x8
us.U.func_80119570_us := 0x80119570:0xA9570:0x8
us.S.000A9578 := 693624 1512
us.U.func_80119B60 := 0x80119B60:0xA9B60:0x54
us.U.func_80119BB4 := 0x80119BB4:0xA9BB4:0x80
us.U.func_80119C34 := 0x80119C34:0xA9C34:0xB4
us.U.func_80119CE8_us := 0x80119CE8:0xA9CE8:0x8
us.S.000A9CF0 := 695536 640
us.U.func_80119F70 := 0x80119F70:0xA9F70:0x70
us.S.000A9FE0 := 696288 340
us.U.func_8011A134 := 0x8011A134:0xAA134:0x48
us.S.000AA17C := 696700 2552
us.U.func_8011AB74_us := 0x8011AB74:0xAAB74:0x8
us.S.000AAB7C := 699260 1572
us.U.func_8011B1A0 := 0x8011B1A0:0xAB1A0:0x104
us.U.func_8011B2A4 := 0x8011B2A4:0xAB2A4:0x70
us.S.000AB314 := 701204 1192
us.U.func_8011B7BC := 0x8011B7BC:0xAB7BC:0x74
us.S.000AB830 := 702512 192
us.U.func_8011B8F0 := 0x8011B8F0:0xAB8F0:0x30
us.S.000AB920 := 702752 192
us.U.func_8011B9E0 := 0x8011B9E0:0xAB9E0:0x30
us.S.000ABA10 := 702992 980
us.U.func_8011BDE4 := 0x8011BDE4:0xABDE4:0x2C
us.S.000ABE10 := 704016 832
us.U.func_8011C150 := 0x8011C150:0xAC150:0x30
us.U.func_8011C180 := 0x8011C180:0xAC180:0x24
us.S.000AC1A4 := 704932 348
us.U.func_8011C300 := 0x8011C300:0xAC300:0x20
us.S.000AC320 := 705312 124
us.U.func_8011C39C_us := 0x8011C39C:0xAC39C:0x8
us.U.func_8011C3A4_us := 0x8011C3A4:0xAC3A4:0x8
us.S.000AC3AC := 705452 3380
us.U.func_8011D0E0 := 0x8011D0E0:0xAD0E0:0x20
us.U.func_8011D100 := 0x8011D100:0xAD100:0x80
us.S.000AD180 := 708992 604
us.U.func_8011D3DC := 0x8011D3DC:0xAD3DC:0x28
us.S.000AD404 := 709636 716
us.U.func_8011D6D0 := 0x8011D6D0:0xAD6D0:0x8
us.S.000AD6D8 := 710360 1320
us.U.func_8011DC00_us := 0x8011DC00:0xADC00:0x8
us.S.000ADC08 := 711688 88
us.U.func_8011DC60 := 0x8011DC60:0xADC60:0x38
us.U.func_8011DC98 := 0x8011DC98:0xADC98:0x60
us.S.000ADCF8 := 711928 72
us.U.func_8011DD40_us := 0x8011DD40:0xADD40:0x8
us.S.000ADD48 := 712008 1704
us.U.func_8011E3F0 := 0x8011E3F0:0xAE3F0:0x44
us.U.func_8011E434 := 0x8011E434:0xAE434:0x54
us.U.func_8011E488 := 0x8011E488:0xAE488:0x54
us.S.000AE4DC := 713948 136
us.U.func_8011E564 := 0x8011E564:0xAE564:0xA8
us.S.000AE60C := 714252 1688
us.U.func_8011ECA4 := 0x8011ECA4:0xAECA4:0xE0
us.S.000AED84 := 716164 2668
us.U.func_8011F7F0 := 0x8011F7F0:0xAF7F0:0x1C
us.S.000AF80C := 718860 9988
us.U.func_80121F10 := 0x80121F10:0xB1F10:0x7C
us.S.000B1F8C := 728972 6636
us.U.func_80123978_us := 0x80123978:0xB3978:0x8
us.S.000B3980 := 735616 7652992
us.PIECES := \
  build/us/slices/00000000.bin \
  build/us/units/func_80076038.bin \
  build/us/slices/00006068.bin \
  build/us/units/func_8007627C.bin \
  build/us/slices/00006390.bin \
  build/us/units/func_80077930.bin \
  build/us/slices/000079CC.bin \
  build/us/units/func_80077A38.bin \
  build/us/slices/00007AD0.bin \
  build/us/units/func_80078D90.bin \
  build/us/slices/00008E2C.bin \
  build/us/units/func_80078F60_us.bin \
  build/us/slices/00008F70.bin \
  build/us/units/func_800793D0.bin \
  build/us/slices/00009474.bin \
  build/us/units/func_8007967C.bin \
  build/us/units/func_80079684.bin \
  build/us/slices/0000968C.bin \
  build/us/units/func_800799C0_us.bin \
  build/us/slices/000099D0.bin \
  build/us/units/func_80079A5C.bin \
  build/us/slices/00009AB4.bin \
  build/us/units/func_80079EFC.bin \
  build/us/slices/00009FA4.bin \
  build/us/units/func_8007A26C_us.bin \
  build/us/slices/0000A36C.bin \
  build/us/units/func_8007AAA0.bin \
  build/us/units/func_8007AAB0.bin \
  build/us/units/func_8007AAC0.bin \
  build/us/units/func_8007AAE4_us.bin \
  build/us/units/func_8007AAF4_us.bin \
  build/us/slices/0000AB04.bin \
  build/us/units/func_8007B1DC_us.bin \
  build/us/slices/0000B1EC.bin \
  build/us/units/func_8007C298.bin \
  build/us/slices/0000C2A0.bin \
  build/us/units/func_8007C33C.bin \
  build/us/slices/0000C344.bin \
  build/us/units/func_8007C6D8.bin \
  build/us/slices/0000C700.bin \
  build/us/units/func_8007D1F8.bin \
  build/us/slices/0000D2A0.bin \
  build/us/units/func_8007D384.bin \
  build/us/slices/0000D42C.bin \
  build/us/units/func_8007E140_us.bin \
  build/us/slices/0000E150.bin \
  build/us/units/func_8007EC38.bin \
  build/us/units/func_8007ECE8.bin \
  build/us/units/func_8007ED98.bin \
  build/us/units/func_8007EE48.bin \
  build/us/slices/0000EEF8.bin \
  build/us/units/func_8007F030_us.bin \
  build/us/slices/0000F040.bin \
  build/us/units/func_8007F060.bin \
  build/us/slices/0000F070.bin \
  build/us/units/func_8007FF68.bin \
  build/us/units/func_8008001C_us.bin \
  build/us/slices/0001011C.bin \
  build/us/units/func_800805C0_us.bin \
  build/us/units/func_800805D0.bin \
  build/us/units/func_800805DC.bin \
  build/us/slices/0001067C.bin \
  build/us/units/func_80081A30.bin \
  build/us/units/func_80081A40_us.bin \
  build/us/slices/00011A50.bin \
  build/us/units/func_80081AC0_us.bin \
  build/us/slices/00011AD0.bin \
  build/us/units/func_800821C0.bin \
  build/us/slices/000121D0.bin \
  build/us/units/func_80085330.bin \
  build/us/slices/000153C8.bin \
  build/us/units/func_80085460.bin \
  build/us/units/func_80085468.bin \
  build/us/slices/00015470.bin \
  build/us/units/func_8008C2DC_us.bin \
  build/us/slices/0001C2EC.bin \
  build/us/units/func_800907CC_us.bin \
  build/us/slices/000208CC.bin \
  build/us/units/func_80090F10.bin \
  build/us/slices/00020F94.bin \
  build/us/units/func_80091608.bin \
  build/us/units/func_800916B8.bin \
  build/us/slices/0002176C.bin \
  build/us/units/func_800917C4.bin \
  build/us/units/func_800917D8.bin \
  build/us/slices/00021814.bin \
  build/us/units/func_80091D04.bin \
  build/us/slices/00021D10.bin \
  build/us/units/func_80092534_us.bin \
  build/us/slices/00022734.bin \
  build/us/units/func_80093F34.bin \
  build/us/slices/00023F3C.bin \
  build/us/units/func_800949B8.bin \
  build/us/slices/000249D8.bin \
  build/us/units/func_80096760.bin \
  build/us/slices/00026768.bin \
  build/us/units/func_80096784.bin \
  build/us/slices/00026834.bin \
  build/us/units/func_800968FC.bin \
  build/us/slices/00026920.bin \
  build/us/units/func_80097B7C.bin \
  build/us/units/func_80097C24.bin \
  build/us/slices/00027C64.bin \
  build/us/units/func_80099CD8.bin \
  build/us/slices/00029D90.bin \
  build/us/units/func_8009E39C.bin \
  build/us/slices/0002E3A4.bin \
  build/us/units/func_800A2EA4.bin \
  build/us/slices/00032F48.bin \
  build/us/units/func_800A3D30.bin \
  build/us/slices/00033DE0.bin \
  build/us/units/func_800A424C.bin \
  build/us/units/func_800A4254.bin \
  build/us/units/func_800A42A4.bin \
  build/us/units/func_800A42B0.bin \
  build/us/units/func_800A42BC.bin \
  build/us/units/func_800A42C4_us.bin \
  build/us/slices/000342D0.bin \
  build/us/units/func_800A4368_us.bin \
  build/us/slices/00034374.bin \
  build/us/units/func_800A4A64.bin \
  build/us/slices/00034B2C.bin \
  build/us/units/func_800A4D10_us.bin \
  build/us/units/func_800A4D1C.bin \
  build/us/slices/00034D34.bin \
  build/us/units/func_800A51E8.bin \
  build/us/units/func_800A52AC.bin \
  build/us/slices/00035348.bin \
  build/us/units/func_800A59E8.bin \
  build/us/slices/00035AA4.bin \
  build/us/units/func_800A66B0_us.bin \
  build/us/units/func_800A66C0.bin \
  build/us/slices/000366C8.bin \
  build/us/units/func_800A68E0_us.bin \
  build/us/units/func_800A68F0_us.bin \
  build/us/slices/00036900.bin \
  build/us/units/func_800A6E10.bin \
  build/us/slices/00036E30.bin \
  build/us/units/func_800A72C8.bin \
  build/us/slices/00037328.bin \
  build/us/units/func_800A74AC.bin \
  build/us/units/func_800A7548.bin \
  build/us/units/func_800A7550.bin \
  build/us/slices/000375EC.bin \
  build/us/units/func_800A76A0.bin \
  build/us/slices/000376BC.bin \
  build/us/units/func_800A7D10.bin \
  build/us/slices/00037DBC.bin \
  build/us/units/func_800A81F0.bin \
  build/us/slices/0003823C.bin \
  build/us/units/func_800A979C.bin \
  build/us/slices/00039850.bin \
  build/us/units/func_800A9B44.bin \
  build/us/units/func_800A9B70.bin \
  build/us/slices/00039C14.bin \
  build/us/units/func_800AA280.bin \
  build/us/units/func_800AA328.bin \
  build/us/slices/0003A3D0.bin \
  build/us/units/func_800AB200.bin \
  build/us/slices/0003B208.bin \
  build/us/units/func_800AB614.bin \
  build/us/slices/0003B61C.bin \
  build/us/units/func_800AB95C.bin \
  build/us/slices/0003B9FC.bin \
  build/us/units/func_800ABFA0.bin \
  build/us/slices/0003BFA8.bin \
  build/us/units/func_800ABFD0.bin \
  build/us/slices/0003C070.bin \
  build/us/units/func_800AC2D0_us.bin \
  build/us/slices/0003C2E0.bin \
  build/us/units/func_800B8750.bin \
  build/us/units/func_800B87F4_us.bin \
  build/us/slices/00048804.bin \
  build/us/units/func_800CE4B0.bin \
  build/us/slices/0005E554.bin \
  build/us/units/func_800DD9E8_us.bin \
  build/us/units/func_800DDA00_us.bin \
  build/us/slices/0006DA08.bin \
  build/us/units/func_800DDCA4.bin \
  build/us/slices/0006DCCC.bin \
  build/us/units/func_800E0B00.bin \
  build/us/slices/00070BC4.bin \
  build/us/units/func_800E1A08_us.bin \
  build/us/slices/00071A14.bin \
  build/us/units/func_800E2614_us.bin \
  build/us/units/func_800E2620_us.bin \
  build/us/slices/0007262C.bin \
  build/us/units/func_800E3460.bin \
  build/us/units/func_800E3470.bin \
  build/us/units/func_800E3480.bin \
  build/us/units/func_800E349C.bin \
  build/us/units/func_800E34B4.bin \
  build/us/slices/00073554.bin \
  build/us/units/func_800E3C18.bin \
  build/us/slices/00073C34.bin \
  build/us/units/func_800E480C.bin \
  build/us/units/func_800E4814_us.bin \
  build/us/slices/0007481C.bin \
  build/us/units/func_800E4D44.bin \
  build/us/slices/00074DF8.bin \
  build/us/units/func_800E5198.bin \
  build/us/slices/000751A0.bin \
  build/us/units/func_800E51B8_us.bin \
  build/us/slices/000751C0.bin \
  build/us/units/func_800E566C.bin \
  build/us/slices/00075688.bin \
  build/us/units/func_800E6A70_us.bin \
  build/us/slices/00076A78.bin \
  build/us/units/func_800E6C14.bin \
  build/us/slices/00076C5C.bin \
  build/us/units/func_800E6CA4.bin \
  build/us/slices/00076D58.bin \
  build/us/units/func_800E6FA0_us.bin \
  build/us/units/func_800E6FA8_us.bin \
  build/us/slices/00076FB0.bin \
  build/us/units/func_800E7718_us.bin \
  build/us/slices/00077724.bin \
  build/us/units/func_800E78BC_us.bin \
  build/us/units/func_800E78C8_us.bin \
  build/us/units/func_800E78D4_us.bin \
  build/us/units/func_800E78E0_us.bin \
  build/us/units/func_800E78EC_us.bin \
  build/us/units/func_800E78F8_us.bin \
  build/us/units/func_800E7904_us.bin \
  build/us/units/func_800E7910_us.bin \
  build/us/units/func_800E791C_us.bin \
  build/us/units/func_800E7928_us.bin \
  build/us/slices/00077934.bin \
  build/us/units/func_800E9894.bin \
  build/us/slices/00079940.bin \
  build/us/units/func_800E99D4.bin \
  build/us/slices/000799E0.bin \
  build/us/units/func_800E9A20_us.bin \
  build/us/units/func_800E9A28_us.bin \
  build/us/slices/00079A30.bin \
  build/us/units/func_800E9DA4.bin \
  build/us/slices/00079E5C.bin \
  build/us/units/func_800EA1B0.bin \
  build/us/slices/0007A1B8.bin \
  build/us/units/func_800EA1FC.bin \
  build/us/slices/0007A2A4.bin \
  build/us/units/func_800EACEC_us.bin \
  build/us/slices/0007AD2C.bin \
  build/us/units/func_800EB07C_us.bin \
  build/us/slices/0007B0E8.bin \
  build/us/units/func_800EB1E8_us.bin \
  build/us/slices/0007B228.bin \
  build/us/units/func_800EB440_us.bin \
  build/us/slices/0007B47C.bin \
  build/us/units/func_800EB4A4_us.bin \
  build/us/slices/0007B4E4.bin \
  build/us/units/func_800EB6D4_us.bin \
  build/us/units/func_800EB71C_us.bin \
  build/us/units/func_800EB764_us.bin \
  build/us/units/func_800EB7AC_us.bin \
  build/us/slices/0007B818.bin \
  build/us/units/func_800EBBB4_us.bin \
  build/us/units/func_800EBBBC_us.bin \
  build/us/slices/0007BBFC.bin \
  build/us/units/func_800EBD74_us.bin \
  build/us/slices/0007BDB4.bin \
  build/us/units/func_800EBE6C_us.bin \
  build/us/slices/0007BEAC.bin \
  build/us/units/func_800ED810.bin \
  build/us/slices/0007D8BC.bin \
  build/us/units/func_800EEBEC.bin \
  build/us/units/func_800EECA0.bin \
  build/us/slices/0007ED5C.bin \
  build/us/units/func_800F2120_us.bin \
  build/us/slices/00082128.bin \
  build/us/units/func_800F3014.bin \
  build/us/slices/000830C8.bin \
  build/us/units/func_800F5128.bin \
  build/us/units/func_800F5178.bin \
  build/us/slices/00085264.bin \
  build/us/units/func_80106D00.bin \
  build/us/units/func_80106D08_us.bin \
  build/us/units/func_80106D10_us.bin \
  build/us/slices/00096D18.bin \
  build/us/units/func_80107168_us.bin \
  build/us/slices/00097170.bin \
  build/us/units/func_80107704_us.bin \
  build/us/slices/0009770C.bin \
  build/us/units/func_80109354.bin \
  build/us/slices/00099364.bin \
  build/us/units/func_8010BC08.bin \
  build/us/slices/0009BC10.bin \
  build/us/units/func_8010DCD0.bin \
  build/us/slices/0009DD78.bin \
  build/us/units/func_801109B8_us.bin \
  build/us/slices/000A09C0.bin \
  build/us/units/func_80110AAC_us.bin \
  build/us/slices/000A0AB4.bin \
  build/us/units/func_80110CA0.bin \
  build/us/slices/000A0D24.bin \
  build/us/units/func_801145D0.bin \
  build/us/slices/000A46A0.bin \
  build/us/units/func_801147A0.bin \
  build/us/units/func_80114828.bin \
  build/us/slices/000A4858.bin \
  build/us/units/func_80115474.bin \
  build/us/units/func_8011588C.bin \
  build/us/slices/000A5A24.bin \
  build/us/units/func_80115C80.bin \
  build/us/slices/000A5D7C.bin \
  build/us/units/func_8011954C.bin \
  build/us/units/func_80119568_us.bin \
  build/us/units/func_80119570_us.bin \
  build/us/slices/000A9578.bin \
  build/us/units/func_80119B60.bin \
  build/us/units/func_80119BB4.bin \
  build/us/units/func_80119C34.bin \
  build/us/units/func_80119CE8_us.bin \
  build/us/slices/000A9CF0.bin \
  build/us/units/func_80119F70.bin \
  build/us/slices/000A9FE0.bin \
  build/us/units/func_8011A134.bin \
  build/us/slices/000AA17C.bin \
  build/us/units/func_8011AB74_us.bin \
  build/us/slices/000AAB7C.bin \
  build/us/units/func_8011B1A0.bin \
  build/us/units/func_8011B2A4.bin \
  build/us/slices/000AB314.bin \
  build/us/units/func_8011B7BC.bin \
  build/us/slices/000AB830.bin \
  build/us/units/func_8011B8F0.bin \
  build/us/slices/000AB920.bin \
  build/us/units/func_8011B9E0.bin \
  build/us/slices/000ABA10.bin \
  build/us/units/func_8011BDE4.bin \
  build/us/slices/000ABE10.bin \
  build/us/units/func_8011C150.bin \
  build/us/units/func_8011C180.bin \
  build/us/slices/000AC1A4.bin \
  build/us/units/func_8011C300.bin \
  build/us/slices/000AC320.bin \
  build/us/units/func_8011C39C_us.bin \
  build/us/units/func_8011C3A4_us.bin \
  build/us/slices/000AC3AC.bin \
  build/us/units/func_8011D0E0.bin \
  build/us/units/func_8011D100.bin \
  build/us/slices/000AD180.bin \
  build/us/units/func_8011D3DC.bin \
  build/us/slices/000AD404.bin \
  build/us/units/func_8011D6D0.bin \
  build/us/slices/000AD6D8.bin \
  build/us/units/func_8011DC00_us.bin \
  build/us/slices/000ADC08.bin \
  build/us/units/func_8011DC60.bin \
  build/us/units/func_8011DC98.bin \
  build/us/slices/000ADCF8.bin \
  build/us/units/func_8011DD40_us.bin \
  build/us/slices/000ADD48.bin \
  build/us/units/func_8011E3F0.bin \
  build/us/units/func_8011E434.bin \
  build/us/units/func_8011E488.bin \
  build/us/slices/000AE4DC.bin \
  build/us/units/func_8011E564.bin \
  build/us/slices/000AE60C.bin \
  build/us/units/func_8011ECA4.bin \
  build/us/slices/000AED84.bin \
  build/us/units/func_8011F7F0.bin \
  build/us/slices/000AF80C.bin \
  build/us/units/func_80121F10.bin \
  build/us/slices/000B1F8C.bin \
  build/us/units/func_80123978_us.bin \
  build/us/slices/000B3980.bin
